#!/bin/bash

map=$1
turns=$2

python tools/playgame.py "python MyBot.py" --map_file $map --log_dir game_logs --turns $turns --player_seed 7 --verbose -e "python tools/sample_bots/python/GreedyBot.py" "python tools/sample_bots/python/GreedyBot.py" "python tools/sample_bots/python/GreedyBot.py" "python tools/sample_bots/python/HunterBot.py" "python tools/sample_bots/python/HunterBot.py"
