#!/bin/bash

map=$1
turns=$2
bot_dir="tools/sample_bots/python/"

python tools/playgame.py "python MyBot.py" --map_file $map --log_dir game_logs --turns $turns --player_seed 7 --verbose -e "python $bot_dir$3" "python $bot_dir$4"
