#!/bin/bash

map=$1
turns=$2
bot="python MyBot.py"

python tools/playgame.py --map_file $map --log_dir game_logs --turns $turns --player_seed 7 --verbose -e "python MyBot.py" "python MyBot.py" "python MyBot.py" "python MyBot.py" "python MyBot.py" "python MyBot.py" 
